ADD: apps 생성 & 모델링
wecode-bootcamp-korea/28-2nd-Sucream-backend pull request #1
Opened 2022-01-11 11:37 UTC by nine57

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- Sucream project 초기 Modeling

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 생성, 수정 시간을 따른 Class table로 구성하여 필요한 Table에 상속 (cores.models.TimeStampModel)
2. Bidding table의 is_buyer 필드를 통해 해당 입찰이 구매자쪽의 입찰인지 판매자쪽의 입찰인지 구분
3. Product table과 user table이 like table을 통해 다대다로 연결되어 있으며, like table 에서 is_like로 관심항목인지 구별
4. Order table의 buyer, seller는 User의 id값을 참조하여 필요한 정보를 필터링 가능

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 유저 flow 관점에서 데이터의 흐름을 이해할 수 있었습니다.
- TimeStampModel 의 사용과 같은 Class의 상속 개념에 대해 remind했습니다.
- 각 필드값의 필요성과 테이블의 연속적인 연결상황에서의 관계 설정에 대해 고민할 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항
- user정보와 order의 관계 설정이 맞는 것인지 관계 설정이 뚜렷하지 않습니다...

2022-01-11 12:43 UTC, Kang-kyunghun requested changes

2022-01-11 12:43 UTC, Kang-kyunghun commented on biddings/models.py
> +    seller         = models.ForeignKey(User, related_name='seller', on_delete=models.CASCADE)
related_name을 언제 사용하는지 생각해보고 related_name을 이용해서 데이터를 가져올 때, 어떤 데이터를 가져오려고 하는지 의미가 알 수 있나 한편 살펴 보시고 수정해 보세요.

2022-01-11 12:43 UTC, Kang-kyunghun commented on cores/models.py
> +
```suggestion
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

```

2022-01-11 12:43 UTC, Kang-kyunghun commented on products/models.py
> +    images        = models.ManyToManyField("Image", related_name="products")
저희 이미지는 M2M 아니고 1:N으로 하기로 하지 않았나요??

2022-01-11 12:43 UTC, Kang-kyunghun commented on products/models.py
> +    url          = models.CharField(max_length=500)
```suggestion
    url = models.CharField(max_length=500)
```

2022-01-11 12:43 UTC, Kang-kyunghun commented on users/models.py
> +    kakao_id = models.CharField(max_length=50)
kakao_id는 IntegerField로 받으시면 됩니다~
공식문서 한 번 확인해 주세요.

2022-01-11 12:48 UTC, sxxk2 commented on users/models.py
> +    kakao_id = models.CharField(max_length=50)
![스크린샷 2022-01-11 오후 9 47 14](https://user-images.githubusercontent.com/83942213/148945319-406fbffe-6306-4a6c-b38b-206e498276ea.png)
혹시 여기서의 app_id 부분일까요 ?

2022-01-11 15:46 UTC, nine57 commented on cores/models.py
> +
수정 완료했습니다.

2022-01-11 15:49 UTC, nine57 commented on products/models.py
> +    images        = models.ManyToManyField("Image", related_name="products")
다른 부분이랑 헷갈렸던 것 같습니다....
1:N으로 수정 완료했습니다!

2022-01-11 15:49 UTC, nine57 commented on products/models.py
> +    url          = models.CharField(max_length=500)
감사합니다. 수정 완료했습니다.

2022-01-11 16:24 UTC, nine57 commented on biddings/models.py
> +    seller         = models.ForeignKey(User, related_name='seller', on_delete=models.CASCADE)
'related_name'은 역참조로 데이터를 가져올 때, "즉 여기서는 User의 객체에서 buyer 또는 seller의 데이터를 역으로 참조해서 가져올 때 쓰게 되며, '(class name)_set' 대신 해당이름을 통해서 가져온다" 라고 알고 있습니다. 

특히나 지금과 같이 동일한 테이블을 참조하는 컬럼일 경우에 역참조를 할 때, 어느쪽의 데이터를 바라보고 참조하는지 알 수 없으므로 'related_name'을 넣어줘야 명확한 값으로 참조할 수 있기 때문에 위와 같이 추가해주었습니다.

지금의 경우에는 user의 입장에서 역참조로 넘어올 때, 유저가 샀던 정보 (=사는사람인 buyer), 또는 유저가 팔았던 정보(=파는사람인 seller)로 관계를 이어줘야 한다고 생각해서 위와 같이 적어주었습니다.

다만, 가져오는 데이터가 단순히 한개의 필드값이 아니라 객체정보를 가져오게 되므로
buyer, seller 보다는 order_buy, order_sell 과 같이 붙이는 것이 더 좋은 표현이라고 생각됩니다.

2022-01-12 01:56 UTC, nine57 commented on users/models.py
> +    kakao_id = models.CharField(max_length=50)
positiveinteger로 수정 했습니다!

2022-01-12 04:52 UTC, Kang-kyunghun requested changes

2022-01-12 04:52 UTC, Kang-kyunghun commented on products/models.py
> +    url = models.CharField(max_length=500)
```suggestion
class Image(models.Model):
    product = models.ForeignKey("Product, on_delete=models.CASCADE)
    url = models.CharField(max_length=500)
```
product가 1이고 image가 N 이기 때문에 다음과 같이 수정해 주세요. 
Product class 도 수정해 주세요.

2022-01-12 04:53 UTC, Kang-kyunghun commented on biddings/models.py
> +    seller         = models.ForeignKey(User, related_name='seller', on_delete=models.CASCADE)
조사 아주 좋습니다~!!!

2022-01-12 07:25 UTC, nine57 commented on products/models.py
> +    url = models.CharField(max_length=500)
수정 완료했습니다!

2022-01-12 08:37 UTC, Kang-kyunghun commented
LGTM

2022-01-12 08:37 UTC, merged