Add: 소셜로그인, 로그인 데코레이터 작성
wecode-bootcamp-korea/28-2nd-Sucream-backend pull request #3
Opened 2022-01-14 04:57 UTC by sxxk2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

카카오 소셜로그인기능을 이용해 회원가입이 대체된 로그인로직을 구현하고, 
추후 로그인이 필요한 로직에 사용 할 수 있게 데코레이터를 만들었습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

users/views.py 
KakaoLoginView
- FE에게 받은 카카오토큰을 이용해 카카오서버에 카카오id값과 이메일을 받음.
- 받은 데이터들을 DB와 비교해 이미 있다면 토큰을 발급.
- DB에 없는데이터라면 DB에 생성 후 토큰 발급

cores/utils.py 
login_decorator
- header에 'Authorization'의 키 값을 가지고 있는 토큰을 조회 후 없다면 에러를 보냄.
- 토큰이 있다면 복호화를 통해 유저의 아이디값을 가져옴

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 실제 유저로써 정말 편리하게 사용하는 소셜로그인 기능이였는데, 직접 구현해보니 뿌듯함을 느꼈습니다.
- 기존의 일반적인 회원가입/로그인 로직이 아닌 새로운방식이였는데, 오히려 소셜로그인 방식이 사용자와 개발자 모두 편리할 수 있는 방법이지 않나 느꼈습니다.

<br />

## :: 기타 질문 및 특이 사항

- user의 모델링에는 카카오아이디, 이메일테이블만 있는데, (실습단계이기때문에) 이메일을 선택항목으로밖에 받을 수 없어 필수항목으로 받을 수 있는 테이블을 생성하고 받아야 할지가 고민입니다.

2022-01-15 09:32 UTC, Kang-kyunghun requested changes

2022-01-15 09:32 UTC, Kang-kyunghun commented on users/tests.py
> +            point    = 10000000
```suggestion
            id       = 1,
	    kakao_id = 123456789,
            email    = '123456789@gmail.com',
            point    = 10000000
```

2022-01-15 09:32 UTC, Kang-kyunghun commented on users/tests.py
> +                    }
```suggestion
        class MockedResponse:
            def json(self):
                return {
                    "id":123456789,
                    "kakao_account": {
                        "email" : "123456789@gmail.com"
                     }
                 }
```

2022-01-15 09:32 UTC, Kang-kyunghun commented on cores/utils.py
> +        return func(self, request,  *args, **kwargs)
```suggestion
        try:
            access_token = request.headers['Authorization']
            payload      = jwt.decode(access_token, SECRET_KEY, ALGORITHM)
            user         = User.objects.get(id=payload['user_id'])
            request.user = user

        except jwt.exceptions.DecodeError:
            return JsonResponse({'MESSAGE': 'INVALID_TOKEN'}, status=401)

        except User.DoesNotExist:
            return JsonResponse({'MESSAGE': 'INVALID_USER'}, status=401)
            
        except KeyError:
            return JsonResponse({'MESSAGE': 'Key_Error'}, status=400)

        return func(self, request,  *args, **kwargs)
```
```python
user = User.objects.get(id=payload['user_id'])
```
해당 부분에서도 keyerror가 발생할 수 있으니 다음과 같이 keyerror을 추가하면 좋을 것 같습니다.

2022-01-15 09:55 UTC, sxxk2 commented on cores/utils.py
> +        return func(self, request,  *args, **kwargs)
수정 완료 후 push 완료 했습니다 !

2022-01-17 01:22 UTC, Kang-kyunghun commented
LGTM

2022-01-17 01:22 UTC, merged